### ISSUE TITLE
Manually zero the gradients 

### ISSUE THREAD

**Issue by cs-zyluo** [jcjohnson/pytorch-examples#14]
https://github.com/jcjohnson/pytorch-examples/blob/659a73cc68fc9d2d68d0c43fb33ff446a2b86c06/autograd/two_layer_net_autograd.py#L37

According to a very recent version of pytorch, this would cause the following error: 'NoneType' object has no attribute 'data'. 
Maybe we should zero the gradients after running the backward pass now.

**Comment by sanjuprk** [comment]
I think it is done in lines 55,56

**Comment by jcjohnson** [comment]
Fixed.
