### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by rajatongit** [jcjohnson/pytorch-examples#27]
I was going through the PyTorch documentation on the webpage: 
https://pytorch.org/tutorials/beginner/pytorch_with_examples.html#tensors

First of all, thanks a lot for the brilliant tutorial. @jcjohnson 

I noticed some typing errors, and thought I should bring it to your notice.

_# dtype = torch.device("cuda:0") # Uncomment this to run on GPU_

This is a line which is repeated several times throughout the tutorial on the aforementioned web page, and hence might be confusing for newbies like me. I think the correct should be

**_# device = torch.device("cuda:0") # Uncomment this to run on GPU_**
Thanks,
Rajat Chhabra

**Comment by jcjohnson** [comment]
I think this is fixed now; feel free to reopen if I'm wrong.
