### ISSUE TITLE
Activation not applied on the output layer

### ISSUE THREAD

**Issue by harshnova** [jcjohnson/pytorch-examples#30]
In Warm-up exercises using Numpy and PyTorch, corresponding to lines
`y_pred = h_relu.dot(w2)` and
`y_pred = h_relu.mm(w2)` respectively, 
I am unable to understand why activation function is not applied to the output neuron to produce the final output? In both the examples, `h_relu` corresponds to the activation function on the hidden layer. Need some understanding on why this activation function is missing on outputs.

**Comment by jcjohnson** [comment]
If you apply ReLU to the output layer then the network cannot predict negative values.
